---
title: 'Subgroup Analysis of respiratory acidosis in eICU '
output: html_document
date: "2023-06-08"
---
load eICU subset data of COPD patients
```{r}
library(mgcv)

source("funs.R")

load("eICU_COPD_subset2.RData")
```


```{r}
eICU_COPD <- eICU_COPD_subset2

eICU_COPD0 <- eICU_COPD[eICU_COPD$oxygen_therapy == "SupplementalOxygen", ]

eICU_COPD1 <- eICU_COPD[eICU_COPD$oxygen_therapy == "SupplementalOxygen" & eICU_COPD$Hypercapnia == "Non-Hypercapnia", ]


eICU_COPD2 <- eICU_COPD[eICU_COPD$oxygen_therapy == "SupplementalOxygen" & eICU_COPD$Hypercapnia == "Hypercapnia", ]

```

```{r}
eICU_pCO2pH <- eICU_COPD[, c("pCO2", "ph")]

```

```{r}
plot(pCO2 ~ ph, data = eICU_pCO2pH, xlab = "pH", main = "eICU-CRD", pch = 4L, ylab = "pCO2 (mmHg)")
```



````{r}
eICU_COPD2_subset1 <- eICU_COPD2[eICU_COPD2$ResAcid == "Acid", ]

eICU_COPD2_subset2 <- eICU_COPD2[eICU_COPD2$ResAcid != "Acid", ]
```

```{r}
Re3_eICU <- GAM_proportion(eICU_COPD2_subset1)

print(Re3_eICU)

Re4_eICU <- GAM_proportion(eICU_COPD2_subset2)

print(Re4_eICU)

```


```{r}
beta_CoI <- array(NA_real_, c(9, 3, 3))

beta_CoI[ , , 1] <- Re2_eICU[9:1, ]

beta_CoI[, , 2] <- Re3_eICU[9:1, ]

beta_CoI[, , 3] <- Re4_eICU[9:1, ]

x_offset <- .30
ylim = range(beta_CoI)
# Set margins to make room for x axis labels.
# Set up empty plot

plot(
  x = 0,
  type = 'n',
  xlim = c(1 - 3 * x_offset, 9 + 3 * x_offset),
  ylim = ylim,
  xlab = expression("SpO"[2]*" range"),
  ylab = "Odds ratio for hospital mortaility",
  xaxt = "n"
)

for (r in 1:9) {
  plot_CI(x = r - x_offset, CI = beta_CoI[r, ,  1], lty=3)
  plot_CI(x = r , CI = beta_CoI[r, ,  2], lty = 4)
  plot_CI(x = r + x_offset, CI = beta_CoI[r, ,  3], lty = 5)
}
abline(h = 1, col = "red")
axis(1, at = 1:9, labels=c("88-92", "89-93", "90-94", "91-95", "92-96", "93-97", "94-98", "95-99", "96-100"))
legend("topright", legend=c("Hypercapnia", "Acidosis", "Non-Acidosis"), lty = 3:5, cex=0.8, bty ="n")
```